# Change these first
owner: Kord-Extensions # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://kordex.dev
  - name: Docs
    url: https://docs.kordex.dev
  - name: Dokka
    url: https://dokka.kordex.dev
  - name: Maven Repo
    url: https://repo.kordex.dev

status-website:
  cname: status.kordex.dev
  logoUrl: https://kordex.dev/logo.png
  name: Kord Extensions Status
  introTitle: "Service status information"
  introMessage: "This is a status page which monitors various services run by Kord Extensions. Powered by Upptime."
  navbar:
    - title: Home
      href: https://kordex.dev
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
